apiVersion: "argoproj.io/v1alpha1"
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/MaxwellGBrown/argocd-tutorial.git"
    targetRevision: HEAD
    path: apps/myapp
  destination:
    # The target cluster to sync with
    server: https://kubernetes.default.svc  # Alias for local k8s
    namespace: myapp  # Created automatically w/ syncPolicy.syncOptions CreateNamespace=true
  syncPolicy:  # Configuration for ArgoCD's gitops-k8s sync
    syncOptions:
      - "CreateNamespace=true"
    automated:
      selfHeal: true  # will rollback if changed resources fail
      prune: true  # allows deleting of removed resources
---
apiVersion: "argoproj.io/v1alpha1"
kind: Application
metadata:
  name: robertshand-hello-world
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/MaxwellGBrown/argocd-tutorial.git"
    targetRevision: HEAD
    path: apps/robertshand-hello-world
  destination:
    server: https://kubernetes.default.svc
    namespace: robertshand-hello-world
  syncPolicy:
    syncOptions:
      - "CreateNamespace=true"
    automated:
      selfHeal: true
      prune: true
